######################################################################
# Automatically generated by qmake (3.0) So. Apr. 2 12:51:56 2017
######################################################################

TEMPLATE = app
TARGET = Project3
INCLUDEPATH += .

QT += core gui widgets

# Input
HEADERS += calculator.h
SOURCES += calculator.cpp main.cpp
